---
sidebar: sidebar 
permalink: trident-docker/volumes-docker.html 
keywords: create volumes, astra trident, trident for docker, docker, docker volume 
summary: 'ボリュームを作成するには、標準を使用します `docker volume` 必要に応じてAstra Tridentドライバ名を指定したコマンド。' 
---
= ボリュームを操作します
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
標準のを使用すると、ボリュームを簡単に作成、クローニング、および削除できます `docker volume` 必要に応じてAstra Tridentドライバ名を指定したコマンド。



== ボリュームを作成します

* デフォルトの名前を使用して、ドライバでボリュームを作成します。
+
[listing]
----
docker volume create -d netapp --name firstVolume
----
* 特定の Astra Trident インスタンスを使用してボリュームを作成します。
+
[listing]
----
docker volume create -d ntap_bronze --name bronzeVolume
----
+

NOTE: 何も指定しない場合 link:volume-driver-options.html["オプション（ Options ）"^]、ドライバのデフォルトが使用されます。

* デフォルトのボリュームサイズを上書きします。次の例を参照して、ドライバで 20GiB ボリュームを作成してください。
+
[listing]
----
docker volume create -d netapp --name my_vol --opt size=20G
----
+

TIP: ボリュームサイズは、オプションの単位（ 10G 、 20GB 、 3TiB など）を含む整数値で指定します。単位を指定しない場合、デフォルトは g ですサイズの単位は、 2 の累乗（ B 、 KiB 、 MiB 、 GiB 、 TiB ）または 10 の累乗（ B 、 KB 、 MB 、 GB 、 TB ）のいずれかです。略記単位では、 2 の累乗が使用されます（ G=GiB 、 T=TiB 、…）。





== ボリュームを削除します

* 他の Docker ボリュームと同様にボリュームを削除します。
+
[listing]
----
docker volume rm firstVolume
----
+

IMPORTANT: を使用する場合 `solidfire-san` driver、上記の例では、ボリュームを削除およびパージします。



Astra Trident for Docker をアップグレードするには、次の手順を実行します。



== ボリュームのクローンを作成します

を使用する場合 `ontap-nas`、 `ontap-san`、 `solidfire-san`および `gcp-cvs storage drivers`Tridentがボリュームをクローニングできます。を使用する場合 `ontap-nas-flexgroup` または `ontap-nas-economy` ドライバ、クローニングはサポートされていません。既存のボリュームから新しいボリュームを作成すると、新しい Snapshot が作成されます。

* ボリュームを調べて Snapshot を列挙します。
+
[listing]
----
docker volume inspect <volume_name>
----
* 既存のボリュームから新しいボリュームを作成します。その結果、新しい Snapshot が作成されます。
+
[listing]
----
docker volume create -d <driver_name> --name <new_name> -o from=<source_docker_volume>
----
* ボリューム上の既存の Snapshot から新しいボリュームを作成します。新しい Snapshot は作成されません。
+
[listing]
----
docker volume create -d <driver_name> --name <new_name> -o from=<source_docker_volume> -o fromSnapshot=<source_snap_name>
----




=== 例

[listing]
----
docker volume inspect firstVolume

[
    {
        "Driver": "ontap-nas",
        "Labels": null,
        "Mountpoint": "/var/lib/docker-volumes/ontap-nas/netappdvp_firstVolume",
        "Name": "firstVolume",
        "Options": {},
        "Scope": "global",
        "Status": {
            "Snapshots": [
                {
                    "Created": "2017-02-10T19:05:00Z",
                    "Name": "hourly.2017-02-10_1505"
                }
            ]
        }
    }
]

docker volume create -d ontap-nas --name clonedVolume -o from=firstVolume
clonedVolume

docker volume rm clonedVolume
docker volume create -d ontap-nas --name volFromSnap -o from=firstVolume -o fromSnapshot=hourly.2017-02-10_1505
volFromSnap

docker volume rm volFromSnap
----


== 外部で作成されたボリュームにアクセス

Tridentを使用すると、外部で作成されたブロックデバイス（またはそのクローン）にTrident *からアクセスできます。Tridentは、パーティションがなく、Astra Tridentでサポートされているファイルシステム（など）の場合にのみ利用できます `ext4`-フォーマット済み `/dev/sdc1` Astra Trident経由ではアクセスできません）。
