---
sidebar: sidebar 
permalink: trident-docker/volume-driver-options.html 
keywords: create volumes, astra trident, trident for docker, docker, docker volume, driver options, ontap, element volumes, cvs, cloud volumes service on gcp, azure netapp files 
summary: ストレージドライバにはそれぞれ異なるオプションがあり、ボリュームの作成時に指定することで結果をカスタマイズできます。構成済みのストレージシステムに適用されるオプションについては、以下を参照してください。 
---
= ドライバ固有のボリュームオプション
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージドライバにはそれぞれ異なるオプションがあり、ボリュームの作成時に指定することで結果をカスタマイズできます。構成済みのストレージシステムに適用されるオプションについては、以下を参照してください。

ボリューム作成処理では、これらのオプションを簡単に使用できます。を使用して、オプションと値を指定します `-o` CLI処理中の演算子。これらは、 JSON 構成ファイルの同等の値よりも優先されます。



== ONTAP ボリュームのオプション

NFS と iSCSI のどちらの場合も、 volume create オプションには次のオプションがあります。

[cols="2*"]
|===
| オプション | 説明 


| `size`  a| 
ボリュームのサイズ。デフォルトは 1GiB です。



| `spaceReserve`  a| 
ボリュームをシンプロビジョニングまたはシックプロビジョニングします。デフォルトはシンです。有効な値はです `none` （シンプロビジョニング）および `volume` （シックプロビジョニング）。



| `snapshotPolicy`  a| 
Snapshot ポリシーが目的の値に設定されます。デフォルトはです `none`つまり、ボリュームに対してSnapshotが自動的に作成されることはありません。ストレージ管理者によって変更されていない限り、「 default 」という名前のポリシーがすべての ONTAP システムに存在し、 6 個の時間単位 Snapshot 、 2 個の日単位 Snapshot 、および 2 個の週単位 Snapshot を作成して保持します。Snapshotに保存されているデータは、にアクセスしてリカバリできます `.snapshot` ボリューム内の任意のディレクトリ内のディレクトリ。



| `snapshotReserve`  a| 
これにより、 Snapshot リザーブの割合が希望する値に設定されます。デフォルト値は no で、 Snapshot ポリシーを選択した場合は ONTAP によって snapshotReserve が選択されます（通常は 5% ）。 Snapshot ポリシーがない場合は 0% が選択されます。構成ファイルのすべての ONTAP バックエンドに対して snapshotReserve のデフォルト値を設定できます。また、この値は、 ONTAP-NAS-エコノミー を除くすべての ONTAP バックエンドでボリューム作成オプションとして使用できます。



| `splitOnClone`  a| 
ボリュームをクローニングすると、そのクローンが原因 ONTAP によって親から即座にスプリットされます。デフォルトはです `false`。クローンボリュームのクローニングは、作成直後に親からクローンをスプリットする方法を推奨します。これは、ストレージ効率化の効果がまったくないためです。たとえば、空のデータベースをクローニングしても時間は大幅に短縮されますが、ストレージはほとんど削減されません。そのため、クローンはすぐにスプリットすることを推奨します。



| `encryption`  a| 
新しいボリュームでNetApp Volume Encryption（NVE）を有効にします。デフォルトはです `false`。このオプションを使用するには、クラスタで NVE のライセンスが設定され、有効になっている必要があります。

NAEがバックエンドで有効になっている場合は、Astra TridentでプロビジョニングされたすべてのボリュームがNAEに有効になります。

詳細については、以下を参照してください。 link:../trident-reco/security-reco.html["Astra TridentとNVEおよびNAEの相互運用性"]。



| `tieringPolicy`  a| 
ボリュームに使用する階層化ポリシーを設定します。これにより、アクセス頻度の低いコールドデータをクラウド階層に移動するかどうかが決まります。

|===
以下は、 NFS * のみ * 用の追加オプションです。

[cols="2*"]
|===
| オプション | 説明 


| `unixPermissions`  a| 
これにより、ボリューム自体の権限セットを制御できます。デフォルトでは、権限はに設定されます ``---rwxr-xr-x`または数値表記0755、およびです `root` が所有者になります。テキスト形式または数値形式のどちらかを使用できます。



| `snapshotDir`  a| 
これをに設定します `true` がを作成します `.snapshot` ボリュームにアクセスしているクライアントから認識できるディレクトリ。デフォルト値はです `false`の可視性を意味します `.snapshot` ディレクトリはデフォルトで無効になっています。一部のイメージ（公式のMySQLイメージなど）が、 `.snapshot` ディレクトリが表示されます。



| `exportPolicy`  a| 
ボリュームで使用するエクスポートポリシーを設定します。デフォルトはです `default`。



| `securityStyle`  a| 
ボリュームへのアクセスに使用するセキュリティ形式を設定します。デフォルトはです `unix`。有効な値はです `unix` および `mixed`。

|===
以下の追加オプションは、 iSCSI * のみ * 用です。

[cols="2*"]
|===
| オプション | 説明 


| `fileSystemType` | iSCSI ボリュームのフォーマットに使用するファイルシステムを設定します。デフォルトはです `ext4`。有効な値はです `ext3`、 `ext4`および `xfs`。 


| `spaceAllocation` | これをに設定します `false` LUNのスペース割り当て機能を無効にします。デフォルト値はです `true`つまり、ボリュームのスペースが不足し、ボリューム内のLUNに書き込みを受け付けられなくなったときに、ONTAP からホストに通知されます。また、このオプションで ONTAP 、ホストでデータが削除された時点での自動スペース再生も有効になります。 
|===


=== 例

以下の例を参照してください。

* 10GiB ボリュームを作成します。
+
[listing]
----
docker volume create -d netapp --name demo -o size=10G -o encryption=true
----
* Snapshot を使用して 100GiB のボリュームを作成します。
+
[listing]
----
docker volume create -d netapp --name demo -o size=100G -o snapshotPolicy=default -o snapshotReserve=10
----
* setuid ビットが有効になっているボリュームを作成します。
+
[listing]
----
docker volume create -d netapp --name demo -o unixPermissions=4755
----


最小ボリュームサイズは 20MiB です。

Snapshotリザーブが指定されていない場合、Snapshotポリシーはです `none`Tridentは0%のSnapshotリザーブを使用します。

* Snapshot ポリシーがなく、 Snapshot リザーブがないボリュームを作成します。
+
[listing]
----
docker volume create -d netapp --name my_vol --opt snapshotPolicy=none
----
* Snapshot ポリシーがなく、カスタムの Snapshot リザーブが 10% のボリュームを作成します。
+
[listing]
----
docker volume create -d netapp --name my_vol --opt snapshotPolicy=none --opt snapshotReserve=10
----
* Snapshot ポリシーを使用し、カスタムの Snapshot リザーブを 10% に設定してボリュームを作成します。
+
[listing]
----
docker volume create -d netapp --name my_vol --opt snapshotPolicy=myPolicy --opt snapshotReserve=10
----
* Snapshot ポリシーを設定してボリュームを作成し、 ONTAP のデフォルトの Snapshot リザーブ（通常は 5% ）を受け入れます。
+
[listing]
----
docker volume create -d netapp --name my_vol --opt snapshotPolicy=myPolicy
----




== Element ソフトウェアのボリュームオプション

Element ソフトウェアのオプションでは、ボリュームに関連付けられているサービス品質（ QoS ）ポリシーのサイズと QoS を指定できます。ボリュームの作成時に、関連付けられているQoSポリシーをを使用して指定します `-o type=service_level` 名称。

Element ドライバを使用して QoS サービスレベルを定義する最初の手順は、少なくとも 1 つのタイプを作成し、構成ファイル内の名前に関連付けられた最小 IOPS 、最大 IOPS 、バースト IOPS を指定することです。

Element ソフトウェアのその他のボリューム作成オプションは次のとおりです。

[cols="2*"]
|===
| オプション | 説明 


| `size`  a| 
ボリュームのサイズ。デフォルト値は 1GiB または設定エントリ ... 「 defaults 」： ｛ 「 size 」：「 5G 」 ｝ 。



| `blocksize`  a| 
512 または 4096 のいずれかを使用します。デフォルトは 512 または config エントリ DefaultBlockSize です。

|===


=== 例

QoS 定義を含む次のサンプル構成ファイルを参照してください。

[listing]
----
{
    "...": "..."
    "Types": [
        {
            "Type": "Bronze",
            "Qos": {
                "minIOPS": 1000,
                "maxIOPS": 2000,
                "burstIOPS": 4000
            }
        },
        {
            "Type": "Silver",
            "Qos": {
                "minIOPS": 4000,
                "maxIOPS": 6000,
                "burstIOPS": 8000
            }
        },
        {
            "Type": "Gold",
            "Qos": {
                "minIOPS": 6000,
                "maxIOPS": 8000,
                "burstIOPS": 10000
            }
        }
    ]
}
----
上記の構成では、 Bronze 、 Silver 、 Gold の 3 つのポリシー定義を使用します。これらの名前は任意です。

* 10GiB の Gold ボリュームを作成します。
+
[listing]
----
docker volume create -d solidfire --name sfGold -o type=Gold -o size=10G
----
* 100GiB Bronze ボリュームを作成します。
+
[listing]
----
docker volume create -d solidfire --name sfBronze -o type=Bronze -o size=100G
----

