---
sidebar: sidebar 
permalink: trident-use/backend_ops_kubectl.html 
keywords: backends, storage system, anf, cvs for aws, cvs for gcp, element, hci, solidfire, ontap, aff, fas, ontap select, configure backends, kubectl, create backends, delete backends, update backends, view backends 
summary: 'を使用してバックエンド管理処理を実行する方法について説明します `kubectl`。' 
---
= kubectl を使用してバックエンド管理を実行します
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
を使用してバックエンド管理処理を実行する方法について説明します `kubectl`。



== バックエンドを削除します

を削除する `TridentBackendConfig`を使用して、Astra Tridentにバックエンドの削除と保持を指示します（ベースはです） `deletionPolicy`）。バックエンドを削除するには、を確認します `deletionPolicy` は削除に設定されています。のみを削除します `TridentBackendConfig`を参照してください `deletionPolicy` はretainに設定されています。これにより、バックエンドがまだ存在し、を使用して管理できるようになります `tridentctl`。

次のコマンドを実行します。

[listing]
----
kubectl delete tbc <tbc-name> -n trident
----
Astra Tridentは、が使用していたKubernetesシークレットを削除しません `TridentBackendConfig`。Kubernetes ユーザは、シークレットのクリーンアップを担当します。シークレットを削除するときは注意が必要です。シークレットは、バックエンドで使用されていない場合にのみ削除してください。



== 既存のバックエンドを表示します

次のコマンドを実行します。

[listing]
----
kubectl get tbc -n trident
----
を実行することもできます `tridentctl get backend -n trident` または `tridentctl get backend -o yaml -n trident` 存在するすべてのバックエンドのリストを取得します。このリストには、で作成されたバックエンドも含まれます `tridentctl`。



== バックエンドを更新します

バックエンドを更新する理由はいくつかあります。

* ストレージシステムのクレデンシャルが変更されている。クレデンシャルを更新する場合、で使用されるKubernetes Secret `TridentBackendConfig` オブジェクトを更新する必要があります。Astra Trident が、提供された最新のクレデンシャルでバックエンドを自動的に更新次のコマンドを実行して、 Kubernetes Secret を更新します。
+
[listing]
----
kubectl apply -f <updated-secret-file.yaml> -n trident
----
* パラメータ（使用する ONTAP SVM の名前など）を更新する必要があります。
+
** 更新できます `TridentBackendConfig` 次のコマンドを使用して、Kubernetesから直接オブジェクトを作成します。
+
[listing]
----
kubectl apply -f <updated-backend-file.yaml>
----
** または、既存の `TridentBackendConfig` 次のコマンドを使用してCRを実行します。
+
[listing]
----
kubectl edit tbc <tbc-name> -n trident
----




[NOTE]
====
* バックエンドの更新に失敗した場合、バックエンドは最後の既知の設定のまま残ります。を実行すると、ログを表示して原因 を特定できます `kubectl get tbc <tbc-name> -o yaml -n trident` または `kubectl describe tbc <tbc-name> -n trident`。
* 構成ファイルで問題を特定して修正したら、 update コマンドを再実行できます。


====