---
sidebar: sidebar 
permalink: trident-use/trident-fsx-examples.html 
keywords: map backends, storage classes, trident backend, ontap-nas, ontap-nas-economy, ontap-nas-flexgroups, options, storageclasses, fsx 
summary: Amazon FSX for ONTAP のバックエンド構成オプションについて説明します。ここでは、バックエンドの設定例を示します。 
---
= FSX（ONTAP の構成オプションと例）
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Amazon FSX for ONTAP のバックエンド構成オプションについて説明します。ここでは、バックエンドの設定例を示します。



== バックエンド構成オプション

バックエンド設定オプションについては、次の表を参照してください。

[cols="3"]
|===
| パラメータ | 説明 | 例 


| `version` |  | 常に 1 


| `storageDriverName` | ストレージドライバの名前 | `ontap-nas`、 `ontap-nas-economy`、 `ontap-nas-flexgroup`、 `ontap-san`、 `ontap-san-economy` 


| `backendName` | カスタム名またはストレージバックエンド | ドライバ名 + "_" + データ LIF 


| `managementLIF` | クラスタ管理 LIF または SVM 管理 LIF の IP アドレス

Fully Qualified Domain Name（FQDN；完全修飾ドメイン名）を指定できます。

IPv6フラグを使用してAstra Tridentをインストールした場合は、IPv6アドレスを使用するように設定できます。IPv6アドレスは、[28e8：d9fb：a825：b7bf：69a8：d02f：9e7b：3555]などの角かっこで定義する必要があります。 | 「 10.0.0.1 」、「 [2001:1234:abcd::fefe] 」 


| `dataLIF` | プロトコル LIF の IP アドレス。

* ONTAP NASドライバ*：データLIFを指定することを推奨します。指定しない場合は、Astra TridentがSVMからデータLIFを取得します。NFSマウント処理に使用するFully Qualified Domain Name（FQDN；完全修飾ドメイン名）を指定して、ラウンドロビンDNSを作成して複数のデータLIF間で負荷を分散することができます。初期設定後に変更できます。を参照してください 。

* ONTAP SANドライバ*: iSCSIには指定しないでくださいTridentがONTAP の選択的LUNマップを使用して、マルチパスセッションの確立に必要なiSCSI LIFを検出します。データLIFが明示的に定義されている場合は警告が生成されます。

IPv6フラグを使用してAstra Tridentをインストールした場合は、IPv6アドレスを使用するように設定できます。IPv6アドレスは、[28e8：d9fb：a825：b7bf：69a8：d02f：9e7b：3555]などの角かっこで定義する必要があります。 |  


| `autoExportPolicy` | エクスポートポリシーの自動作成と更新を有効にします[ブーリアン]。

を使用する `autoExportPolicy` および `autoExportCIDRs` ネットアップのAstra Tridentなら、エクスポートポリシーを自動的に管理できます。 | `false` 


| `autoExportCIDRs` | KubernetesのノードIPをフィルタリングするCIDRのリスト `autoExportPolicy` が有効になります。

を使用する `autoExportPolicy` および `autoExportCIDRs` ネットアップのAstra Tridentなら、エクスポートポリシーを自動的に管理できます。 | 「[0.0.0.0/0]、「::/0」」」 


| `labels` | ボリュームに適用する任意の JSON 形式のラベルのセット | "" 


| `clientCertificate` | クライアント証明書の Base64 エンコード値。証明書ベースの認証に使用されます | "" 


| `clientPrivateKey` | クライアント秘密鍵の Base64 エンコード値。証明書ベースの認証に使用されます | "" 


| `trustedCACertificate` | 信頼された CA 証明書の Base64 エンコード値。任意。証明書ベースの認証に使用されます。 | "" 


| `username` | クラスタまたはSVMに接続するためのユーザ名。クレデンシャルベースの認証に使用されます。たとえば、vsadminのように指定します。 |  


| `password` | クラスタまたはSVMに接続するためのパスワード。クレデンシャルベースの認証に使用されます。 |  


| `svm` | 使用する Storage Virtual Machine | SVM管理LIFが指定されている場合に生成されます。 


| `storagePrefix` | SVM で新しいボリュームをプロビジョニングする際に使用するプレフィックスを指定します。

作成後に変更することはできません。このパラメータを更新するには、新しいバックエンドを作成する必要があります。 | `trident` 


| `limitAggregateUsage` | * Amazon FSx for NetApp ONTAPには指定しないでください。*

提供された `fsxadmin` および `vsadmin` アグリゲートの使用状況を取得し、Astra Tridentを使用して制限するために必要な権限が含まれていない。 | 使用しないでください。 


| `limitVolumeSize` | 要求されたボリュームサイズがこの値を超えている場合、プロビジョニングが失敗します。

また、qtreeおよびLUN用に管理するボリュームの最大サイズも制限します `qtreesPerFlexvol` オプションを使用すると、FlexVol あたりの最大qtree数をカスタマイズできます。 | “”（デフォルトでは適用されません） 


| `lunsPerFlexvol` | FlexVol あたりの最大LUN数。有効な範囲は50、200です。

SANのみ。 | `100` 


| `debugTraceFlags` | トラブルシューティング時に使用するデバッグフラグ。例： {"API" ： false 、 "method" ： true}

使用しないでください `debugTraceFlags` トラブルシューティングを実行していて、詳細なログダンプが必要な場合を除きます。 | null 


| `nfsMountOptions` | NFSマウントオプションをカンマで区切ったリスト。

Kubernetes永続ボリュームのマウントオプションは通常はストレージクラスで指定されますが、ストレージクラスでマウントオプションが指定されていない場合、Astra Tridentはストレージバックエンドの構成ファイルで指定されているマウントオプションを使用します。

ストレージクラスや構成ファイルにマウントオプションが指定されていない場合、Astra Tridentは関連付けられた永続的ボリュームにマウントオプションを設定しません。 | "" 


| `nasType` | NFSボリュームまたはSMBボリュームの作成を設定

オプションはです `nfs`、 `smb`、またはnull。

*をに設定する必要があります `smb` SMBボリューム。*をnullに設定すると、デフォルトでNFSボリュームが使用されます。 | `nfs` 


| `qtreesPerFlexvol` | FlexVol あたりの最大 qtree 数。有効な範囲は [50 、 300] です。 | `200` 


| `smbShare` | 次のいずれかを指定できます。Microsoft管理コンソールまたはONTAP CLIを使用して作成されたSMB共有の名前、またはAstra TridentでSMB共有を作成できるようにする名前。

このパラメータは、Amazon FSx for ONTAPバックエンドに必要です。 | `smb-share` 


| `useREST` | ONTAP REST API を使用するためのブーリアンパラメータ。* テクニカルプレビュー *

`useREST` は、**テクニカルプレビュー**として提供されています。テスト環境では、本番環境のワークロードでは推奨されません。に設定すると `true`Astra Tridentは、ONTAP REST APIを使用してバックエンドと通信します。

この機能にはONTAP 9.11.1以降が必要です。また、使用するONTAP ログインロールにはへのアクセス権が必要です `ontap` アプリケーション：これは事前定義されたによって満たされます `vsadmin` および `cluster-admin` ロール。 | `false` 


| `aws` | AWS FSx for ONTAPの構成ファイルでは、次の項目を指定できます。
- `fsxFilesystemID`：AWS FSxファイルシステムのIDを指定します。
- `apiRegion`：AWS APIリージョン名。
- `apikey`：AWS APIキー。
- `secretKey`：AWSシークレットキー。 | ``
``


`""`
`""`
`""` 


| `credentials` | AWS Secret Managerに保存するFSx SVMのクレデンシャルを指定します。
- `name`：シークレットのAmazon Resource Name（ARN）。SVMのクレデンシャルが含まれています。
- `type`:に設定 `awsarn`。
を参照してください link:https://docs.aws.amazon.com/secretsmanager/latest/userguide/create_secret.html["AWS Secrets Managerシークレットの作成"^] を参照してください。 |  
|===


=== 更新 `dataLIF` 初期設定後

初期設定後にデータLIFを変更するには、次のコマンドを実行して、更新されたデータLIFを新しいバックエンドJSONファイルに指定します。

[listing]
----
tridentctl update backend <backend-name> -f <path-to-backend-json-file-with-updated-dataLIF>
----

NOTE: PVCが1つ以上のポッドに接続されている場合は、対応するすべてのポッドを停止してから、新しいデータLIFを有効にするために稼働状態に戻す必要があります。



== ボリュームのプロビジョニング用のバックエンド構成オプション

これらのオプションを使用して、のデフォルトプロビジョニングを制御できます `defaults` 設定のセクション。例については、以下の設定例を参照してください。

[cols="3"]
|===
| パラメータ | 説明 | デフォルト 


| `spaceAllocation` | space-allocation for LUN のコマンドを指定します | `true` 


| `spaceReserve` | スペースリザベーションモード：「 none 」（シン）または「 volume 」（シック） | `none` 


| `snapshotPolicy` | 使用する Snapshot ポリシー | `none` 


| `qosPolicy` | 作成したボリュームに割り当てる QoS ポリシーグループ。ストレージプールまたはバックエンドごとに、QOSPolicyまたはadaptiveQosPolicyのいずれかを選択します。

Trident が Astra で QoS ポリシーグループを使用するには、 ONTAP 9.8 以降が必要です。

非共有のQoSポリシーグループを使用して、各コンスティチュエントに個別にポリシーグループを適用することを推奨します。共有 QoS ポリシーグループにより、すべてのワークロードの合計スループットに対して上限が適用されます。 | 「」 


| `adaptiveQosPolicy` | アダプティブ QoS ポリシーグループ：作成したボリュームに割り当てます。ストレージプールまたはバックエンドごとに、QOSPolicyまたはadaptiveQosPolicyのいずれかを選択します。

経済性に影響する ONTAP - NAS ではサポートされません。 | 「」 


| `snapshotReserve` | Snapshot「0」用にリザーブされているボリュームの割合 | 状況 `snapshotPolicy` はです `none`、 `else` 「」 


| `splitOnClone` | 作成時にクローンを親からスプリットします | `false` 


| `encryption` | 新しいボリュームでNetApp Volume Encryption（NVE）を有効にします。デフォルトはです `false`。このオプションを使用するには、クラスタで NVE のライセンスが設定され、有効になっている必要があります。

NAEがバックエンドで有効になっている場合は、Astra TridentでプロビジョニングされたすべてのボリュームがNAEに有効になります。

詳細については、以下を参照してください。 link:../trident-reco/security-reco.html["Astra TridentとNVEおよびNAEの相互運用性"]。 | `false` 


| `luksEncryption` | LUKS暗号化を有効にします。を参照してください link:../trident-reco/security-reco.html#Use-Linux-Unified-Key-Setup-(LUKS)["Linux Unified Key Setup（LUKS；統合キーセットアップ）を使用"]。

SANのみ。 | "" 


| `tieringPolicy` | 使用する階層化ポリシー	`none` | `snapshot-only` ONTAP 9.5より前のSVM-DR構成の場合 


| `unixPermissions` | 新しいボリュームのモード。

* SMBボリュームは空にしておきます。* | 「」 


| `securityStyle` | 新しいボリュームのセキュリティ形式。

NFSのサポート `mixed` および `unix` セキュリティ形式

SMBはをサポートします `mixed` および `ntfs` セキュリティ形式 | NFSのデフォルトはです `unix`。

SMBのデフォルト： `ntfs`。 
|===


== 構成例

.SMBホリユウムノストレエシクラスノセツテイ
[%collapsible]
====
を使用します `nasType`、 `node-stage-secret-name`および `node-stage-secret-namespace`を使用して、SMBボリュームを指定し、必要なActive Directoryクレデンシャルを指定できます。SMBボリュームは、を使用してサポートされます `ontap-nas` ドライバーのみ。

[listing]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nas-smb-sc
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
  trident.netapp.io/nasType: "smb"
  csi.storage.k8s.io/node-stage-secret-name: "smbcreds"
  csi.storage.k8s.io/node-stage-secret-namespace: "default"
----
====
.Secret Managerを使用したAWS FSx for ONTAPの設定
[%collapsible]
====
[listing]
----
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-ontap-nas
spec:
  version: 1
  storageDriverName: ontap-nas
  backendName: tbc-ontap-nas
  svm: svm-name
  aws:
    fsxFilesystemID: fs-xxxxxxxxxx
  managementLIF:
  credentials:
    name: "arn:aws:secretsmanager:us-west-2:xxxxxxxx:secret:secret-name"
    type: awsarn
----
====